import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'dog-01',
    name: 'Roupa Cirúrgica para Cães (Tamanho 01)',
    description: 'Para peitoral de 32cm e peso entre 1-2kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['01'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-02',
    name: 'Roupa Cirúrgica para Cães (Tamanho 02)',
    description: 'Para peitoral de 34cm e peso entre 2-3kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['02'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-03',
    name: 'Roupa Cirúrgica para Cães (Tamanho 03)',
    description: 'Para peitoral de 36cm e peso entre 3-4kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['03'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-04',
    name: 'Roupa Cirúrgica para Cães (Tamanho 04)',
    description: 'Para peitoral de 38cm e peso entre 5-6kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['04'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-05',
    name: 'Roupa Cirúrgica para Cães (Tamanho 05)',
    description: 'Para peitoral de 40cm e peso entre 7-8kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['05'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-06',
    name: 'Roupa Cirúrgica para Cães (Tamanho 06)',
    description: 'Para peitoral de 42cm e peso entre 9-10kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['06'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-07',
    name: 'Roupa Cirúrgica para Cães (Tamanho 07)',
    description: 'Para peitoral de 44cm e peso entre 11-12kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['07'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-08',
    name: 'Roupa Cirúrgica para Cães (Tamanho 08)',
    description: 'Para peitoral de 46cm e peso entre 13-14kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['08'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-09',
    name: 'Roupa Cirúrgica para Cães (Tamanho 09)',
    description: 'Para peitoral de 48cm e peso entre 15-17kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['09'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-10',
    name: 'Roupa Cirúrgica para Cães (Tamanho 10)',
    description: 'Para peitoral de 56cm e peso entre 18-20kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['10'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-11',
    name: 'Roupa Cirúrgica para Cães (Tamanho 11)',
    description: 'Para peitoral de 60cm e peso entre 21-23kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['11'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'dog-12',
    name: 'Roupa Cirúrgica para Cães (Tamanho 12)',
    description: 'Para peitoral de 64cm e peso entre 24-26kg.',
    category: 'dog',
    imageId: 'dog-surgical-shirt-unisex',
    sizes: ['12'],
    genders: ['male', 'female'],
    price: 20.8,
  },
  {
    id: 'cat-00',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 00)',
    description: 'Para peitoral de 28cm e peso de 1,5kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['00'],
    genders: ['unisex'],
    price: 16.8,
  },
  {
    id: 'cat-01',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 01)',
    description: 'Para peitoral de 30cm e peso entre 2-3kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['01'],
    genders: ['unisex'],
    price: 16.8,
  },
  {
    id: 'cat-02',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 02)',
    description: 'Para peitoral de 32cm e peso entre 3-4kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['02'],
    genders: ['unisex'],
    price: 16.8,
  },
  {
    id: 'cat-03',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 03)',
    description: 'Para peitoral de 34cm e peso entre 4-5kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['03'],
    genders: ['unisex'],
    price: 16.8,
  },
  {
    id: 'cat-04',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 04)',
    description: 'Para peitoral de 36cm e peso entre 5-6kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['04'],
    genders: ['unisex'],
    price: 16.8,
  },
  {
    id: 'cat-05',
    name: 'Roupa Cirúrgica para Gatos (Tamanho 05)',
    description: 'Para peitoral de 38cm e peso entre 7-8kg.',
    category: 'cat',
    imageId: 'cat-surgical-shirt-unisex',
    sizes: ['05'],
    genders: ['unisex'],
    price: 12.8,
  },
];
